name: Build Serotonin

on:
  push:
    branches: A12restart

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Make IPA
      run: ./build.sh
      
    - uses: actions/upload-artifact@v3
      with:
       name: IPA Do
       path: build/Serotonin.ipa
